name: Cloud workstation

on:
  workflow_dispatch:

jobs:
  workstation:
    runs-on: ubuntu-latest
    timeout-minutes: 360 # Hard job limit

    steps:
      - name: Checkout Workstation Repository
        uses: actions/checkout@v4

      - name: Make Scripts Executable
        run: chmod +x ./scripts/*

      - name: Bootstrap Base System
        run: ./scripts/bootstrap.sh

      - name: Connect to Tailscale Network with SSH
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_OAUTH_SECRET }}
          tags: tag:ci
          ssh: true

      - name: Launch Persistent Session
        run: ./scripts/start-session.sh
